server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 200m
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    jsp:
      init-parameters:
        development: true
  error:
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: game
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:/assets/,classpath:/static/,classpath:/html/
  mvc:
    static-path-pattern: /**
    view:
      prefix: /views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  messages:
    encoding: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: mysql-pool
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: select 1
      validation-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      readOnly: false
  thymeleaf:
    enabled: false
    cache: false
    mode: HTML
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**,site/**,cache/**,head/**

# mybatis配置
mybatis:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
  type-aliases-package: com.fit.entity
  mapper-locations: classpath:mapper/*.xml

debug: false

logging:
  level:
    web: info
  file:
    path: ./target/log

fit:
  session: FIT_SESSION